project_id = "cawzmommjifzohakwwwx"

[functions.school-student-approval]
verify_jwt = false

[functions.study-chat]
verify_jwt = false

[functions.generate-quiz]
verify_jwt = false

[functions.notify-school-registration]
verify_jwt = false

[functions.send-weekly-report]
verify_jwt = false


[functions.secure-auth]
verify_jwt = false

[functions.get-students]
verify_jwt = false

[functions.analyze-answer]
verify_jwt = false
